### ISSUE TITLE
Implement CD pipeline

### ISSUE THREAD

**Issue by njogz** [medic/cht-interoperability#71]
**Describe the issue**
Right now the process of deploying new versions of the mediator is very manual and involves creating a new Docker image that is pushed to docker hub and then manually deployed via Kubernetes.

**Describe the improvement you'd like**
The deployment process can be automated in continuous deployment workflow to ensure new versions are deployed in a fast, efficient and less error prone manner

**Describe alternatives you've considered**
None.

**Tasks**

- [x] Set up Github Action to automatically build a Docker image when a commit is made on the main branch
- [x] Push the new image to docker hub
- [ ] Set up a process for updating the image being run by the kubernetes cluster to the new image

**Comment by Phil-Mwago** [comment]
@njogz should we move this to in-progress column?

**Comment by witash** [comment]
closing this as stale because not sure we actually need or want the third step "Set up a process for updating the image being run by the kubernetes cluster to the new image"

We can reopen later if it becomes relevant again
